
import "./globals.css";

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "tracer study | Home",
//   description: "Generated by tracer study",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={`antialiased text-black bg-white`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
