import Hero from "@/components/layouts/hero";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "tracer study | Home",
  description: "Generated by tracer study",
};

export default function Home() {
  return (
    <main>
      <Hero/>
    </main>
  );
}
